### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by kattatzu** [CriptoPagos/cryptomkt-api-client-php#1]
Hola,

se me presento este error usando PHP 7.2.6.

PHP Fatal error:  **Cannot use 'Object' as class name as it is reserved in** **/Users/kattatzu/Sites/okane/vendor/sasco/cryptomkt-api-client/lib/Object.php** on line **29**

In Object.php line 29:

  Cannot use 'Object' as class name as it is reserved

No es buena idea usar palabras reservadas como nombre de clases, xD

Saludos

**Comment by estebandelaf** [comment]
resuelto con merge https://github.com/CriptoPagos/cryptomkt-api-client-php/pull/2 gracias por el cambio.
